spring:
  application:
    name: spring-skeleton
  data:
    mongodb:
      database: embeded_db
      uri: localhost

server:
  port: 8080

web:
  client:
    log-request: true #log webclient requests

via-cep:
  client:
    url: https://viacep.com.br/
